import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const OUT = new URL("../out/", import.meta.url);
const DEST = new URL("../../chain/src/abis/", import.meta.url);
const CONTRACTS = {
  FeeController: "feeController",
  TokenFactory: "tokenFactory",
  Multisend: "multisend",
  LockVault: "lockVault",
  VaultFactory: "vaultFactory",
  PositionVault: "positionVault",
  ArcVesting: "arcVesting",
  VestingFactory: "vestingFactory",
  ProPass: "proPass",
  TradeSimulator: "tradeSimulator",
};
/**
 * Contracts that are never deployed but run from their runtime code, placed at an address with an eth_call state override
 * (Inspector's trade simulation). Their runtime bytecode is exported too, without the CBOR metadata solc appends (its last
 * two bytes give its length): that trailer is never executed, and leaving it out keeps the exported code identical across
 * machines whatever the metadata hash covers.
 */
const RUNTIME = new Set(["TradeSimulator"]);

function withoutMetadata(hex) {
  const code = hex.startsWith("0x") ? hex.slice(2) : hex;
  const length = parseInt(code.slice(-4), 16);
  const trailer = (length + 2) * 2;
  if (!Number.isFinite(length) || trailer > code.length || code.slice(-trailer, -trailer + 2) !== "a2") {
    throw new Error("runtime bytecode has no CBOR metadata trailer where one was expected");
  }
  return `0x${code.slice(0, -trailer)}`;
}

mkdirSync(DEST, { recursive: true });
for (const [contract, file] of Object.entries(CONTRACTS)) {
  const { abi, deployedBytecode } = JSON.parse(readFileSync(new URL(`${contract}.sol/${contract}.json`, OUT), "utf8"));
  let body = `// Generated by packages/contracts/scripts/export-abis.mjs. Do not edit.\nexport const ${file}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  if (RUNTIME.has(contract)) body += `\nexport const ${file}Runtime = "${withoutMetadata(deployedBytecode.object)}" as const;\n`;
  writeFileSync(new URL(`${file}.ts`, DEST), body);
  console.log(`wrote abis/${file}.ts (${abi.length} entries)`);
}
