import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const OUT = new URL("../out/", import.meta.url);
const DEST = new URL("../../chain/src/abis/", import.meta.url);
const CONTRACTS = { FeeController: "feeController", TokenFactory: "tokenFactory", Multisend: "multisend" };

mkdirSync(DEST, { recursive: true });
for (const [contract, file] of Object.entries(CONTRACTS)) {
  const { abi } = JSON.parse(readFileSync(new URL(`${contract}.sol/${contract}.json`, OUT), "utf8"));
  const body = `// Generated by packages/contracts/scripts/export-abis.mjs. Do not edit.\nexport const ${file}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(new URL(`${file}.ts`, DEST), body);
  console.log(`wrote abis/${file}.ts (${abi.length} entries)`);
}
